### ISSUE TITLE
Access dialogue state from skills

### ISSUE THREAD

**Issue by dmzubr** [deepmipt/dp-agent#104]
Hi there!
Thanks for cool bot framework.

I want to fill a kind of data form for user with dp-agent bot.
Bot with user are filling this form step-by-step.
Suppose that extracted data should be stored in dialogue state to avoid any other storages out of the context of dp-agent features.
And the last step is confirmation, when all data is filled.

I want to access dialogue state information from skills (is it ok?).
According to proposed project's architecture
(this image: https://static.tildacdn.com/tild3164-3762-4439-a131-336437363736/Untitled_Diagram-DP_.jpg) all pipe components are able to access dialogues states.

Based on examples - in the service of Skill  (like in any other pipe component) we have an access to HTTP request only.
And it contains only array of sentences. So - even if I will try to request data directly from MongoDB (not from dialogue state service) - I even don't have a dialogue identifier.

Probably, I missed some basics in understanding of dp-agent pipe. :)
Some, could you please then explain the logic...

**Comment by ShulevA** [comment]
Hi @dmzubr, you should use "dialog_formatter": "dp_formatters: full_dialog" in pipeline settings or not use dialog_formatter at all.
